name: DG Baccarat Detector

on:
  schedule:
    # 每 5 分钟跑一次（GitHub 最小 cron 为 5 分钟）
    - cron: '*/5 * * * *'
  workflow_dispatch: {} # 允许手动触发

jobs:
  run-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install playwright browsers
          playwright install --with-deps

      - name: Run DG detector
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DG_URLS: ${{ secrets.DG_URLS }} # optional, space-separated two urls
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/dg_detector.py
