name: DG Monitor (looped every 6 hours, inner 5-min loops)

on:
  schedule:
    - cron: '0 */6 * * *'  # 每 6 小时触发一次，job 内循环做连续 5 分钟检测（这样更稳定）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 360   # 6 hours, job 内部循环 72 次（72*300s ≈ 6hrs）
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies & browsers
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.39.0 opencv-python-headless numpy pillow requests
          playwright install chromium

      - name: Run monitor (loop)
        env:
          DG_BOT_TOKEN: "8134230045:AAH6C_H53R_J2RH98fGTqZFHsjkKALhsTh8"
          DG_CHAT_ID: "485427847"
          DG_URL1: "https://dg18.co/wap/"
          DG_URL2: "https://dg18.co/"
          TZ_OFFSET: "+08:00"
          LOOP_ITER: "72"          # 72 iterations -> 72 * 5 minutes = 360 minutes (6 hours)
          SLEEP_SECONDS: "300"     # 300s = 5 minutes
        run: |
          python scripts/monitor_dg_loop.py
