name: DG Monitor

on:
  schedule:
    # run every 5 minutes
    - cron: "*/5 * * * *"
  workflow_dispatch: {}  # allow manual trigger

permissions:
  contents: write  # allow writing state.json back to repo
  id-token: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install playwright browsers
          python -m playwright install chromium

      - name: Run monitor
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT:  ${{ secrets.TG_CHAT }}
          DG_URL1:  "https://dg18.co/wap/"
          DG_URL2:  "https://dg18.co/"
          MIN_BOARDS_FOR_POW: "3"
          MID_LONG_REQ: "2"
          COOLDOWN_MINUTES: "10"
          MIN_BLOB_SIZE: "6"
          # GitHub repository & token available in Actions env
        run: |
          python main.py
