name: DG Monitor 24x7

on:
  schedule:
    - cron: "*/5 * * * *"   # 每5分钟自动运行
  workflow_dispatch:         # 也可手动点运行

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 12
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (Playwright + CV)
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.46.0 opencv-python-headless numpy pillow requests pytz
          python -m playwright install --with-deps chromium

      - name: Run monitor
        env:
          # 可选：你也可以在 Settings > Secrets > Actions 里设置 TG_TOKEN/TG_CHAT_ID 覆盖
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
        run: |
          python monitor.py

      - name: Save state (for duration & ETA)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "update state [skip ci]"
            git push
          fi
