name: DG Monitor (every 5 minutes)

on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分钟执行一次
  workflow_dispatch:

permissions:
  contents: write   # 允许写回 repo（state.json）

jobs:
  run-detector:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install deps & Playwright browsers
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install --with-deps

      - name: Run detector
        env:
          TELEGRAM_TOKEN: 8134230045:AAH6C_H53R_J2RH98fGTqZFHsjkKALhsTh8
          TELEGRAM_CHAT_ID: 485427847
          DG_URL_1: https://dg18.co/wap/
          DG_URL_2: https://dg18.co/
          TZ: "Asia/Kuala_Lumpur"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python detector.py
