name: DG Monitor (every-5-min)

# schedule every 5 minutes (GitHub cron min granularity 5min)
on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write    # allow commit state.json back to repo

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install Playwright browsers
          python -m playwright install --with-deps

      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN || '' }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID || '' }}
          # If you prefer to hardcode token/chat id (NOT RECOMMENDED),
          # the script has defaults that will be used.
        run: |
          python monitor.py
