name: DG Monitor

on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分钟执行一次（GitHub 最低粒度通常允许 */5）
  workflow_dispatch:        # 允许手动触发

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Playwright browsers
          python -m playwright install --with-deps

      - name: Run detector
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python detect.py

      - name: Commit updated state.json (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json || true
          git commit -m "Update state from action run" || echo "no change"
          git push || echo "push failed"
