name: DG Monitor (with history aggregator)

on:
  schedule:
    - cron: '*/5 * * * *'    # 每5分钟运行主监测
    - cron: '0 2 * * *'      # 每天 UTC 02:00 运行历史聚合（可修改为你希望的时间）
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Export secrets
        run: |
          echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}" >> $GITHUB_ENV
          echo "MIN_BOARDS_FOR_PAW=3" >> $GITHUB_ENV
          echo "MID_LONG_REQ=2" >> $GITHUB_ENV
          echo "COOLDOWN_MINUTES=10" >> $GITHUB_ENV
          echo "HISTORY_LOOKBACK_DAYS=28" >> $GITHUB_ENV
          echo "HISTORY_PROB_THRESHOLD=0.35" >> $GITHUB_ENV

      - name: Run monitor
        run: |
          python main.py

      - name: Commit state and last_summary if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json history_db.json history_stats.json last_summary.json || true
          git diff --staged --quiet || (git commit -m "Update DG monitor state/history" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  aggregate-history:
    runs-on: ubuntu-latest
    needs: monitor
    if: github.event_name == 'schedule' && github.event.schedule == '0 2 * * *' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run aggregator
        run: |
          python history_aggregator.py

      - name: Commit history_stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add history_stats.json history_db.json || true
          git diff --staged --quiet || (git commit -m "Update history stats" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
