name: DG Monitor

on:
  schedule:
    # run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright==1.43.0 requests opencv-python-headless pillow numpy
          # install playwright browsers
          playwright install --with-deps

      - name: Run monitor
        env:
          # GITHUB_TOKEN is automatically provided by Actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python monitor.py
