name: DG Monitor (every 5 minutes)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

           - name: Export secrets
        run: |
          echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}" >> $GITHUB_ENV
          # 如果你想用 secrets 覆盖默认值，可以在仓库 Secrets 新增 MIN_BOARDS_FOR_PAW/MID_LONG_REQ;
          # 若没有设置，就写入默认值 3 / 2
          if [ -n "${{ secrets.MIN_BOARDS_FOR_PAW }}" ]; then
            echo "MIN_BOARDS_FOR_PAW=${{ secrets.MIN_BOARDS_FOR_PAW }}" >> $GITHUB_ENV
          else
            echo "MIN_BOARDS_FOR_PAW=3" >> $GITHUB_ENV
          fi
          if [ -n "${{ secrets.MID_LONG_REQ }}" ]; then
            echo "MID_LONG_REQ=${{ secrets.MID_LONG_REQ }}" >> $GITHUB_ENV
          else
            echo "MID_LONG_REQ=2" >> $GITHUB_ENV
          fi
          # 同理 COOLDOWN 可选
          if [ -n "${{ secrets.COOLDOWN_MINUTES }}" ]; then
            echo "COOLDOWN_MINUTES=${{ secrets.COOLDOWN_MINUTES }}" >> $GITHUB_ENV
          else
            echo "COOLDOWN_MINUTES=10" >> $GITHUB_ENV
          fi

      - name: Run DG monitor
        run: |
          python main.py

      - name: Commit state (if changed)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json last_run_summary.json || true
          git diff --staged --quiet || (git commit -m "Update DG monitor state" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
