name: DG Monitor

on:
  schedule:
    # every 5 minutes (GitHub cron min granularity is 5 minutes)
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
          # install playwright browsers
          python -m playwright install --with-deps chromium

      - name: Run DG monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          DG_URL_1: ${{ secrets.DG_URL_1 }}
          DG_URL_2: ${{ secrets.DG_URL_2 }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GH Actions token for commit
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          python detect_dg.py
