name: DG Monitor

on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分钟运行一次
  workflow_dispatch:        # 允许手动触发测试

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # playwright 需要安装浏览器
          python -m playwright install chromium

      - name: Run DG monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # 下面两个是备选环境变量（若你想直接用 repo 中的默认也可）
          #DG_LINK1: https://dg18.co/
          #DG_LINK2: https://dg18.co/wap/
        run: |
          python main.py

      - name: Commit status.json back if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if git status --porcelain | grep status.json; then
            git add status.json
            git commit -m "update status.json by workflow"
            git push
          else
            echo "status.json not changed"
          fi
