name: DG Monitor (every 5 minutes)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install deps & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run monitor
        env:
          TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          MIN_BOARDS_FOR_PAW: ${{ secrets.MIN_BOARDS_FOR_PAW || '3' }}
          MID_LONG_REQ: ${{ secrets.MID_LONG_REQ || '2' }}
          MID_MULTI_ROW_REQ: ${{ secrets.MID_MULTI_ROW_REQ || '3' }}
          COOLDOWN_MINUTES: ${{ secrets.COOLDOWN_MINUTES || '10' }}
        run: |
          python main.py

      - name: Commit state files if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json last_run_summary.json historical_events.json || true
          git diff --staged --quiet || (git commit -m "update state from action" && git push)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
