name: DG Monitor

on:
  schedule:
    # every 5 minutes (GitHub allows a limited cron granularity; schedule expressions are min 5 mins)
    - cron: '*/5 * * * *'
  workflow_dispatch: {}

permissions:
  contents: write   # 允许写回仓库（commit state.json）
jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo (persist credentials)
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # install playwright browsers
          python -m playwright install chromium

      - name: Run monitor
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}   # 推荐把 tokens 存在 secrets，而不是硬编码
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python monitor.py

      - name: Show state
        run: |
          echo "state file content:"
          cat state.json || true
