name: DG Monitor

on:
  schedule:
    - cron: '*/5 * * * *'  # every 5 minutes
  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Cache python deps (pip)
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache dg state
        uses: actions/cache@v4
        id: dgstate
        with:
          path: .dg_state
          key: dgstate-${{ runner.ref }}
          restore-keys: |
            dgstate-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # Playwright browsers
          python -m playwright install --with-deps

      - name: Run monitor
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
          DG_URL1: ${{ secrets.DG_URL1 }}
          DG_URL2: ${{ secrets.DG_URL2 }}
          MIN_BOARDS_FOR_POW: '3'
          MID_LONG_REQ: '2'
          COOLDOWN_MINUTES: '10'
        run: |
          python main.py

      - name: Save dg state (no-op; cache step will store .dg_state next run)
        if: always()
        run: |
          ls -la .dg_state || true
