name: DG Monitor (every 5m)

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: dg-monitor
  cancel-in-progress: true

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Export secrets and params
        run: |
          echo "TG_BOT_TOKEN=${{ secrets.TG_BOT_TOKEN }}" >> $GITHUB_ENV
          echo "TG_CHAT_ID=${{ secrets.TG_CHAT_ID }}" >> $GITHUB_ENV
          echo "MIN_BOARDS_FOR_PAW=3" >> $GITHUB_ENV
          echo "MID_LONG_REQ=2" >> $GITHUB_ENV
          echo "COOLDOWN_MINUTES=10" >> $GITHUB_ENV
          echo "MIN_POINTS_FOR_REAL_BOARD=40" >> $GITHUB_ENV
          echo "MAX_WAIT_SECONDS=30" >> $GITHUB_ENV
          echo "RETRY_ATTEMPTS=2" >> $GITHUB_ENV


      - name: Run monitor
        run: |
          python main.py

      - name: Commit state if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add state.json last_run_summary.json || true
          if ! git diff --staged --quiet; then
            git commit -m "update state $(date -u +%Y%m%d%H%M%S)" || true
            git push || true
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
