name: DG Monitor

on:
  schedule:
    - cron: '*/5 * * * *'   # 每 5 分钟运行一次
  workflow_dispatch:        # 允许手动触发

permissions:
  contents: write

jobs:
  monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Configure Git (avoid exit code 128)
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m playwright install chromium

      - name: Run DG monitor
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }} 
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # 如果你不使用 secrets（脚本内已有默认），可注释上面两行
        run: |
          python main.py || echo "main.py returned non-zero but handled"

      - name: Commit status.json back if changed
        run: |
          git add status.json || true
          if git diff --cached --quiet; then
            echo "status.json not changed"
          else
            git commit -m "update status.json by workflow" || echo "commit failed"
            git push origin HEAD || echo "push failed"
          fi
